### ISSUE TITLE
Ability to rotate/flip screen

### ISSUE THREAD

**Issue by thepulserifle** [MiSTer-devel/Arcade-Astrocade_MiSTer#5]
If the core permits, would it be possible to flip the screen? With the varying differences in tate cores, it would be useful to be able to rotate this display instead of forcing a monitor reseat.

**Comment by MacroFPGA** [comment]
It uses scan line interrupts to update the screen so if you force it to draw the other way up it gets lots of screen glitches. so not easily done without double buffering.
